import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SleePoke',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-Hant">
      <body className={inter.className}>
        <main className="container mx-auto my-8 max-w-4xl px-4 text-slate-800 md:px-0" style={{
          scrollbarGutter: 'stable',
        }}>
          <h1 className="text-3xl">SleePoke</h1>
          <hr />
          {children}
        </main>
      </body>
    </html>
  );
}
